### PR TITLE
utils crash 

### PR DESCRIPTION
**Pull request by Ardaa001**
When I run the plugin, an error like this came up:

Undefined constant "CLADevs\VanillaX\utils\PATH"" (EXCEPTION) in "plugins/VanillaX-4.0/src/CLADevs/VanillaX/utils/Utils" at line 40
--- Stack trace ---
  #0 plugins/VanillaX-4.0/src/CLADevs/VanillaX/configuration/features/BlockFeature(21): CLADevs\VanillaX\utils\Utils::getBlockIdsMap()
  #1 plugins/VanillaX-4.0/src/CLADevs/VanillaX/configuration/SettingManager(25): CLADevs\VanillaX\configuration\features\BlockFeature->__construct()
  #2 plugins/VanillaX-4.0/src/CLADevs/VanillaX/VanillaX(46): CLADevs\VanillaX\configuration\SettingManager->__construct()

### CODE REVIEW

**Comment by khIbrahim** [comment]
oh yeah my bad, i update it. try and tell me if it working

**Comment by xXNiceYT** [comment]
u still need to merge with custom block_id_map etc to be able to get new blocks

**Comment by khIbrahim** [comment]
yeah, i don't even know why i remove it lol

**Comment by xXNiceYT** [comment]
😆

**Pull request closed without merging**
