### PR TITLE
Fix internal pm4

### PR DESCRIPTION
**Pull request by ItsRealNise**

### CODE REVIEW

**Comment by ItsRealNise** [comment]
Now i fix command block

**Review by xXNiceYT — COMMENTED** [review]
“Fix internal pm4” commit, evid and data aren’t variables in LevelEventPacket anymore in 4.0 forgot to update that

**Review by xXNiceYT — COMMENTED** [review]
For “Fix command block internal” commit, $pk->blockPosition = BlockPosition::fromVector3($tile->getPosition()) would be better suited

**Review by xXNiceYT — COMMENTED** [review]
for commit “something change” you forgot to change pk->data to 4.0 one

**Review by supercrafter333 — APPROVED** [review]
Gr8 job!

**Pull request closed without merging**
