### PR TITLE
Change some method

### PR DESCRIPTION
**Pull request by AIPTU**

### CODE REVIEW

**Review by xXNiceYT — COMMENTED** [review]
my previous game rule code was suppose to give ability to console users to run /gamerule without being in game lol this defeats the purpose other than that it looks good

**Comment by AIPTU** [comment]
Happy now?

**Comment by xXNiceYT** [comment]
Very happy

**Comment by AIPTU** [comment]
Review now and merge

**Comment by AIPTU** [comment]
Lol `TypeError: "Argument 1 passed to CLADevs\VanillaX\enchantments\EnchantmentManager::registerEnchantment() must be an instance of pocketmin
e\item\enchantment\Enchantment, instance of CLADevs\VanillaX\enchantments\EnchantmentManager given, called in phar://aiptu/pmmp/plugins/VanillaX.phar/src/CLADevs/VanillaX/enchantments/EnchantmentManager.php on line 37" (EXCEPTION) in "
plugins/vanillax (1).phar/src/CLADevs/VanillaX/enchantments/EnchantmentManager" at line
 43`

**Comment by xXNiceYT** [comment]
> Lol `TypeError: "Argument 1 passed to CLADevs\VanillaX\enchantments\EnchantmentManager::registerEnchantment() must be an instance of pocketmin e\item\enchantment\Enchantment, instance of CLADevs\VanillaX\enchantments\EnchantmentManager given, called in phar://aiptu/pmmp/plugins/VanillaX.phar/src/CLADevs/VanillaX/enchantments/EnchantmentManager.php on line 37" (EXCEPTION) in " plugins/vanillax (1).phar/src/CLADevs/VanillaX/enchantments/EnchantmentManager" at line 43`

thats bc you made EnchantmentManager an trait lol

**Comment by AIPTU** [comment]
You forgot this
`TypeError: "Argument 2 passed to CLADevs\VanillaX\blocks\utils\TileUtils::generateTile() must be of the type int, string given, called in phar://aiptu/pmmp/plugins/VanillaX.phar/src/CLADevs/VanillaX/blocks/block/ShulkerBoxBlock.php on line 51" (EXCEPTION) in "plugins/VanillaX.phar/src/CLADevs/VanillaX/blocks/utils/TileUtils" at line 21`

**Comment by AIPTU** [comment]
Let me find another bug lol

**Comment by xXNiceYT** [comment]
> generateTile

hm ill check it in bit got class lol

**Pull request merged**
